name: Lint, Format & Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  run-linters:
    name: Lint anf format
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository (branch head commit)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Node.js dependencies
        run: |
          npm ci

      - name: Run formatter
        run: npx prettier --check .

      - name: Run Eslint
        run: npx eslint .

      - name: Run Stylelint
        run: npx stylelint **/*.{css,scss,sass}
